name: Coolify NodeJS and Supabase Deployment
description:
  Deploys a mono-repo application with a Nixpacks frontend and Supabase backend
  to Coolify.
author: Jonathan Bell

branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  deployment_app_uuid:
    description:
      The UUID of the Coolify GitHub app to use for generating deployments
    required: true
  base_deployment_url:
    description:
      The base URL to deploy the web application to. This is used to generate
      the deployment URL.
    required: false
    default: 'dev.pawtograder.net'
  ephemeral:
    description:
      Whether to deploy the application as ephemeral (will be deleted after 24
      hours).
    required: false
    default: false
    type: boolean
  coolify_api_url:
    description: The URL of the Coolify API.
    required: true
    default: 'https://api.coolify.io'
  coolify_api_token:
    description: The token for the Coolify API.
    required: true
  coolify_project_uuid:
    description: The UUID of the Coolify project to deploy to.
    required: true
  coolify_environment_uuid:
    description: The UUID of the Coolify environment to deploy to.
    required: true
    default: 'f0c00s0s8g88ock4swc0w4w8'
  coolify_environment_name:
    description: The name of the Coolify environment to deploy to.
    required: true
  coolify_server_uuid:
    description: The UUID of the Coolify server to deploy to.
    required: false
  coolify_supabase_api_url:
    description:
      The URL of the Supabase deployment service. See
      https://github.com/pawtograder/supabase-coolify-deployment
    required: true
  cleanup_service_uuid:
    description:
      The UUID of the service to clean up. This is used to clean up the
      deployment after the deployment is complete.
    required: false
    default: ''
    type: string
  cleanup_app_uuid:
    description:
      The UUID of the app to clean up. This is used to clean up the deployment
      after the deployment is complete.
    required: false
    default: ''
    type: string
  reset_supabase_db:
    description:
      Whether to reset the Supabase database. This is used to reset the Supabase
      database for the staging deployment.
    required: false
    default: false
    type: boolean
  bugsink_dsn:
    description:
      The DSN for the Bugsink service. This is used to send errors to the
      Bugsink service.
    required: false
    default: ''
    type: string
  discord_webhook_url:
    description:
      The Discord webhook URL to send deployment notifications to. If provided,
      a message with deployment details and secrets will be posted to the
      channel.
    required: false
    default: ''
    type: string
  github_token:
    description:
      GitHub token for posting deployment status comments on PRs. If provided
      and this is a PR, a comment with the deployment URL and status will be
      posted to the PR.
    required: false
    default: ''
    type: string

# Define your outputs here.
outputs:
  supabase_url:
    description: The URL of the newly deployed Supabase service.
  supabase_service_role_key:
    description: The service role key for the newly deployed Supabase service.
  supabase_anon_key:
    description: The anon key for the newly deployed Supabase service.
  app_url:
    description: The URL of the newly deployed frontend web application.
  service_uuid:
    description: The UUID of the newly deployed service.
  app_uuid:
    description: The UUID of the newly deployed web application.
  cleanup_performed:
    description:
      Whether a cleanup was performed (set to 'true' when PR is closed and
      resources are deleted).
  deleted_service_uuid:
    description: The UUID of the deleted service (when cleanup was performed).
  deleted_app_uuid:
    description: The UUID of the deleted app (when cleanup was performed).

runs:
  using: node20
  main: dist/index.js
